services:
  - mdillon/postgis:10
  - redis:latest

variables:
  POSTGRES_DB: locomotion_test
  POSTGRES_USER: locomotion
  POSTGRES_PASSWORD: locomotion

image: php:7.3

stages:
  - test

before_script:
  - apt-get remove cmdtest
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - curl -sL https://deb.nodesource.com/setup_10.x | bash
  - apt-get install curl git wget unzip libpq-dev nodejs yarn -yqq
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
  - docker-php-ext-install pdo_pgsql

cache:
  paths:
    - resources/app/node_modules/
    - vendor/

locomotion:test:
  stage: test
  script:
    - php composer.phar install
    - php artisan migrate --env testing
    - php artisan passport:install --env testing
    - vendor/bin/phpunit
    - cd resources/app && yarn
    - cd resources/app && yarn lint
