# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
services:
  - postgis/postgis:10-2.5-alpine
  - redis:latest

variables:
  POSTGRES_DB: locomotion_test
  POSTGRES_USER: locomotion
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust

image: php:7.3

stages:
  - test

before_script:

cache:
  paths:
    - resources/app/node_modules/
    - vendor/

test:prettier:
  image: node:15
  stage: test
  script:
    - npm install --global prettier @prettier/plugin-php
    - npx prettier . --list-different

test:phpunit:
  stage: test
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  script:
    - apt-get update -yqq
    - apt-get install curl git wget unzip libpq-dev libjpeg-dev libpng-dev libxpm-dev libzip-dev postgresql-client -yqq
    - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
    - cp .env.testing .env
    - pecl install xdebug
    - docker-php-ext-install pdo_pgsql pgsql gd zip
    - php composer.phar install
    - docker-php-ext-enable xdebug
    - psql -h postgis__postgis -U locomotion -w locomotion_test -c 'CREATE EXTENSION unaccent;';
    - psql -h postgis__postgis -U locomotion -w locomotion_test -c 'CREATE EXTENSION citext;';
    - php artisan migrate --env testing
    - php artisan passport:install --env testing
    - export XDEBUG_MODE="coverage"
    - vendor/bin/phpunit --coverage-cobertura=php-coverage.xml -d memory_limit=-1 --coverage-text --colors=never
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: php-coverage.xml

test:jest:
  image: node:15
  stage: test
  script:
    - cd resources/app
    - npm install
    - npm run test
sast:
  variables:
    SAST_EXCLUDED_ANALYZERS:
      bandit, brakeman, flawfinder, gosec, kubesec, nodejs-scan,
      pmd-apex, security-code-scan, sobelow, spotbugs
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
