services:
  - mdillon/postgis:10
  - redis:latest
  - node:10

variables:
  POSTGRES_DB: locomotion_test
  POSTGRES_USER: locomotion
  POSTGRES_PASSWORD: locomotion

image: php:7.3

stages:
  - test

before_script:
  - apt-get install curl git wget unzip libpq-dev -yqq
  - npm install -g yarn
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
  - docker-php-ext-install pdo_pgsql

cache:
  paths:
    - resources/app/node_modules/
    - vendor/

locomotion:test:
  stage: test
  script:
    - php composer.phar install
    - php artisan migrate --env testing
    - vendor/bin/phpunit
    - cd resources/app && yarn
    - cd resources/app && yarn lint
    
