services:
  - postgres:latest
  - redis:latest

variables:
  POSTGRES_DB: locomotion_test
  POSTGRES_USER: locomotion
  POSTGRES_PASSWORD: locomotion

image: php:7.3

stages:
  - test

before_script:
  - apt-get update -yqq
  - apt-get install curl git wget unzip -yqq
  - apt-get install postgresql-client libpq-dev postgis -yqq
  - PGPASSWORD=locomotion psql -h postgres -U locomotion locomotion_test -c 'CREATE EXTENSION postgis;';
  - curl -sL https://deb.nodesource.com/setup_10.x | bash
  - apt-get install -yqq nodejs
  - wget https://composer.github.io/installer.sig -O - -q | tr -d '\n' > installer.sig
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php -r "if (hash_file('SHA384', 'composer-setup.php') === file_get_contents('installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php'); unlink('installer.sig');"
  - docker-php-ext-install pdo_pgsql
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

cache:
  paths:
    - resources/app/node_modules/
    - vendor/

locomotion:test:
  stage: test
  script:
    - php composer.phar install
    - php artisan migrate --env testing
    - vendor/bin/phpunit
    - cd resources/app && yarn
    - cd resources/app && yarn lint
    
