apiVersion: v1
kind: Secret
metadata:
  name: colocauto-secret
type: Opaque
data:
  database.name: # put base64 encrypted data here
  database.user: # put base64 encrypted data here
  database.password: # put base64 encrypted data here
  minio.user: # put base64 encrypted data here
  minio.password: # put base64 encrypted data here
  passport.clientId: # put base64 encrypted data here
  passport.clientSecret: # put base64 encrypted data here
